apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: "raneg49895@idcbill.com"
    privateKeySecretRef: #used to store secret key for the http challenge
      name: letsencrypt-prod
    solvers:
      - http01:
          ingress:
            class: nginx